{% set name = "xeus-python-shell" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python-shell/archive/refs/tags/{{ version }}.tar.gz
  sha256: 664889c3a849392bc1a7572e8af5337f0ca52ce568c5f0e50e35b06c0626a031

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.6
    - pip
  run:
    - python  >=3.6
    - ipython  >=7.21,<8
    - debugpy >=1.4,<2

test:
  imports:
    - xeus_python_shell
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyter-xeus/xeus-python-shell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The xeus-python core python logic.
  dev_url: https://github.com/jupyter-xeus/xeus-python-shell

extra:
  recipe-maintainers:
    - JohanMabille
    - martinRenou
