{% set name = "xeus-python-shell" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python-shell/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7b180c4248e0afe2acaac61a80563aa85e1081ee116ec36c286e3104c5c455ef

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  commands:
    - echo "tests in outputs"

outputs:
  - name: xeus-python-shell-raw
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
      run_constrained:
        - debugpy >=1.4,<2
    test:
      requires:
        - pip
      imports:
        - xeus_python_shell

  - name: xeus-python-shell
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - {{ pin_subpackage("xeus-python-shell-raw", exact=True) }}
        - ipython  >=7.21,<9
    test:
      requires:
        - pip
      imports:
        - xeus_python_shell

about:
  home: https://github.com/jupyter-xeus/xeus-python-shell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The xeus-python core python logic.
  dev_url: https://github.com/jupyter-xeus/xeus-python-shell

extra:
  recipe-maintainers:
    - JohanMabille
    - martinRenou
