{% set name = "xeus-python-shell" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python-shell/archive/refs/tags/{{ version }}.tar.gz
  sha256: f0b7fb3457e327f0cd29dde1f585758606f178c00bd0927d1b138702a72acba7

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.6
    - pip
  run:
    - python  >=3.6
    - ipython  >=7.21,<9
  run_constrained:
    - debugpy >=1.4,<2

test:
  imports:
    - xeus_python_shell

about:
  home: https://github.com/jupyter-xeus/xeus-python-shell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The xeus-python core python logic.
  dev_url: https://github.com/jupyter-xeus/xeus-python-shell

extra:
  recipe-maintainers:
    - JohanMabille
    - martinRenou
